spring:
    mvc:
        servlet:
            path: /
    datasource:
        url: jdbc:postgresql://localhost:5432/itmo-abit-fetcher
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    flyway:
        enabled: true
        schemas: itmo_abit_fetcher
        locations: classpath:db/migration

crnk:
    path-prefix: /api/v1/iaf